version: '3'

services:
  web:
    build: .
    image: ealagtash/portfolio
    ports:
      - 80:80
    restart: "on-failure"
name: cosign-installer
uses: sigstore/cosign-installer@v3.1.2
            