version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/app/static
    depends_on:
      - web
    restart: "on-failure"
  web:
    build: .
    command: sh -c "
      python3 manage.py migrate &&
      python3 manage.py collectstatic --noinput &&
      gunicorn Ehsan.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/home/app
      - static_volume:/home/app/generated-statics
    ports:
      - 8000:8000
    image: ealagtash/portfolio
    restart: "on-failure"


volumes:
  static_volume: